### ISSUE TITLE
[Minor/Major?] Cities that don't exist sometimes show up and are given search results.

### ISSUE THREAD

**Issue by isabelgiang** [YumMe/YumMe#38]
Steps for Reproduction.
1. Search Pokekona, MA
2. View addresses of returned results.

Instead of returning restaurants for Pokekona, MA, results are returned for Boston, MA.
Maybe this isn't a valid search query? I'm assuming it is, since it was suggested in the drop-down.
** EDIT **: I just Googled this city and it doesn't exist. 

I haven't tried many other test cases, but this may also apply to other cities as well.
In the console, I see a 404 Not Found error after searching.

**Comment by leemeli** [comment]
Thanks for the feedback!!! Pokekona is the Hawaiian word for Boston (not sure why), our search will work for any alternative city name but list it as the most common word. We will look into the 404 error in the console, thanks!

**Comment by tgents** [comment]
I got the same issue. I somehow got 'boringugurin, KY' as a suggestion.

**Comment by leemeli** [comment]
Thanks for the feedback @tgents! Boringugurin, KY is another name (in a different language) for the city "Bowling Green, KY". The search functionality is multi-language, you can try any language (to my knowledge). For instance in Chinese, Seattle is 西雅圖. You can try copy pasting the first character of 西雅圖, and when you click on the suggestion it'll take you to Seattle!

**Comment by greycabb** [comment]
For cities such as Pokekona which are the names of cities in different languages, we have decided to keep these since they make YumMe more accessible to people who may not know the English names of cities, and since both the Geonames and Foursquare API seem to support being able to search for these, we have kept them here as well.

However, we have removed cities that Foursquare did not recognize as valid city names (and thus no results appeared), such as lowercase "boringugurin" (generally cities that appeared with the first letter lowercase), so these should no longer appear in the dropdown menu with the next patch!

Also the "404 Not Found" at build/null error has been fixed.
