### ISSUE TITLE
Major: Cannot open any restaurant modals in Firefox

### ISSUE THREAD

**Issue by zmbc** [YumMe/YumMe#39]
Steps:
- Search any city
- Click on any restaurant

There's an error in the console:
![consoleerror](https://cloud.githubusercontent.com/assets/13357648/26795613/2b331b28-49db-11e7-9cd6-bacfe64ca1cc.png)

This only reproduces for me on Firefox. If it helps, I'm using Firefox 53.0.3 on Ubuntu.

**Comment by lkhwa** [comment]
Changed to minor issue.

"Minor. Functionality can be used to accomplish the intended task, but requires **a workaround to be used successfully.**" - in this case, the workaround for being able to see modals is using a different browser, such as Chrome.

**Comment by lkhwa** [comment]
This is now fixed with these commits: [1](https://github.com/YumMe/YumMe/commit/a6a4d79833f79be20fcc1f9f395d7b60c75b1c55), [2](https://github.com/YumMe/YumMe/commit/8e7f6f85693b7da33b684a1df16ab7da55387a41), and [3](https://github.com/YumMe/YumMe/commit/acf305a05b2fbe6749a2571ef3c95da5a8a368da). Master branch updated.
