### ISSUE TITLE
[Minor] Pictures for each restaurant are appearing twice for each, very large for laptop screen.

### ISSUE THREAD

**Issue by DianaCondon** [YumMe/YumMe#40]
Two pictures appear on the home screen, making users only able to see one or two restaurants at a time.
<img width="553" alt="screen shot 2017-06-05 at 11 42 08 am" src="https://cloud.githubusercontent.com/assets/10899670/26798081/1ed6d366-49e4-11e7-8a52-8f75494fe47a.png">

**Comment by greycabb** [comment]
Which browser were you using when you got this bug?

*Edit by Leanne: issue was replicate with Safari, will be addressed in patch.

**Comment by lkhwa** [comment]
This is now fixed with these commits: [1](https://github.com/YumMe/YumMe/commit/a6a4d79833f79be20fcc1f9f395d7b60c75b1c55), [2](https://github.com/YumMe/YumMe/commit/8e7f6f85693b7da33b684a1df16ab7da55387a41), and [3](https://github.com/YumMe/YumMe/commit/acf305a05b2fbe6749a2571ef3c95da5a8a368da). Master branch updated.
