### ISSUE TITLE
[Minor] all pictures are doubled in restaurant detail page as well

### ISSUE THREAD

**Issue by DianaCondon** [YumMe/YumMe#41]
Had to scroll a long way to see all three different pictures before getting to the restaurant information.

<img width="845" alt="screen shot 2017-06-05 at 11 45 18 am" src="https://cloud.githubusercontent.com/assets/10899670/26798209/7d5abd26-49e4-11e7-9b7a-2a49f3fb1b45.png">

**Comment by lkhwa** [comment]
This is now fixed with these commits: [1](https://github.com/YumMe/YumMe/commit/a6a4d79833f79be20fcc1f9f395d7b60c75b1c55), [2](https://github.com/YumMe/YumMe/commit/8e7f6f85693b7da33b684a1df16ab7da55387a41), and [3](https://github.com/YumMe/YumMe/commit/acf305a05b2fbe6749a2571ef3c95da5a8a368da). Master branch updated.
