### ISSUE TITLE
[Minor] Location services slightly off

### ISSUE THREAD

**Issue by FXStrato** [YumMe/YumMe#42]
I gave the application location services, and it says that I'm in Yarrow Point, WA when I'm currently right next to UW Campus. Not that it's too big of an issue, but something that might be fixable through the API? If not, that's fine.

**Comment by lkhwa** [comment]
Thanks for the feedback! Could you paste your browser url when using the current location? It should have the longitutde and latitude, which we'll use to look into this issue further.

**Comment by isabelgiang** [comment]
I experienced the same issue with my location being registered as Yarrow Point, WA.
The browser url was https://yumme.github.io/YumMe/my-app/build/#/search?lat=47.6643681&long=-122.29582589999998.

**Comment by greycabb** [comment]
Due to limitations with the W3C Geolocation API which we used, we are unfortunately unable to solve this problem 100%. The Geolocation API uses four different techniques to find an estimate of the user's current location, which do not always work: GPS, Mobile Network Location, Wifi Positioning, and IP Address Location.

Results seem to be the most accurate on Wifi or on mobile data, but less accurate with Ethernet like on most desktop computers. Sadly we are unable to improve these methods directly as they are a part of the API and out of scope.

[Geolocation API Location Sourcing Details](https://en.wikipedia.org/wiki/W3C_Geolocation_API#Location_Sources)


However, with the latest patch we have implemented some countermeasures to try and make the user's location from the API more accurate, or warn the user if the results are likely inaccurate:

- We have added the enableHighAccuracy option for all Geolocation API calls, which may make the calls more accurate at the expense of runtime, but this is not guaranteed to make the location 100% accurate.

- Secondly, we listen for the accuracy returned by the Geolocation API call, which is approximately how much certainty the API is with our location, in meters. If the accuracy is less than 200 meters then the current location is likely accurate, and now arning will be displayed. However, if the accuracy is returned as more than 200 meters, then the user's current location is likely inaccurate, and YumMe will now warn the user if that location is inaccurate!
