### ISSUE TITLE
location seems not right

### ISSUE THREAD

**Issue by yipang** [YumMe/YumMe#46]
When I click on the icon to use my current location, it sometimes show the default location.

**Comment by greycabb** [comment]
in the url when this happens, does it say lat=undefined and long=undefined?

**Comment by greycabb** [comment]
This is now fixed

Previously there was a 3 second delay after the Geolocation API call to get current latitude and longitude: this delay was there since Geolocation is asynchronous so there needs to be some delay before we go to the search results page with the latitude and longitude.

If Latitude and Longitude could not be retrieved within 3 seconds then it fails, taking the user to the default location, Seattle WA.

Now, when the Geolocation API is called, it checks every 0.2 seconds until latitude and longitude are retrieved and then goes to the Search Results page.

It's also faster with higher internet speeds than before, taking a minimum of 0.2 seconds to go to Search Results page instead of the previous 3 seconds.
