### ISSUE TITLE
Search city autofill not the first on the list

### ISSUE THREAD

**Issue by jkuelz** [YumMe/YumMe#47]
Not a huge deal, but it would be nice to know how the restaurants are being ordered/presented to the user (miles, popularity, alphabetical, etc). Additionally, clicking enter on the autofill list did not give me the results for the first city on the list, it gave me the results for the second.
1. typed in "danville"
2. the drop down autopopulated, the first being "danville, ca" so I clicked enter.
3. the results showed restaurants for "danville, va" without telling me directly, I had to find out by clicking on the restaurants. The top just said, "Now viewing results for: danville" with no state specifications.
I would've assumed that by clicking enter it would've showed me the results for the first on the list (danville, ca) rather than the second on the list (danville, va).

**Comment by greycabb** [comment]
Now fixed in master

If search query does not contain a state, and the search query is a substring of the first search suggestion, it now searches for the first search suggestion that appears.

Note that if search suggestions have not loaded yet, it will still have the old behavior of loading whatever Foursquare deems is the first option for the city name entered.
