### ISSUE TITLE
Cannot get results for non-city name or zip code queries 

### ISSUE THREAD

**Issue by Sungdukkang** [YumMe/YumMe#48]
Search queries beyond just a city name or zip code yield no results. For example, I searched “greenwood seattle” and I got no results. Basically, I cannot search by neighborhood.

**Comment by lkhwa** [comment]
Hi! Thanks for your feedback 👍 

While searching by neighborhood would be a useful function to have, we unfortunately cannot accomodate this due to the limitations of the Foursquare API. You can read more about it [here](https://developer.foursquare.com/docs/venues/search).

Basically, Foursquare can look up restaurants by longitude/latitude (which we use when you click the location pointer icon), or by "city, state" (used when you type city/select city from our dropdown menu). 

As this issue is outside our scope, we will be closing it.
